### ISSUE TITLE
More doc and example? How to listen `Ctrl + 3` and `Space`?

### ISSUE THREAD

**Issue by 1c7** [Clipy/Magnet#28]
## Second, I am confused about the syntax
```swift
if let keyCombo = KeyCombo(keyCode: 11, carbonModifiers: 4352) {
   let hotKey = HotKey(identifier: "CommandControlB", keyCombo: keyCombo, target: self, action: #selector())
   hotKey.register() // or HotKeyCenter.shared.register(with: hotKey)
}
```
What `keyCode: 11` mean?
Where `carbonModifiers: 4352` come from?
Does `identifier: "CommandControlB"` matter? or it only used for `unregister`?

## Third, What if I want listen `Ctrl + 3` and `Space`?
```swift
if let keyCombo = KeyCombo(keyCode: [What should I put here?], carbonModifiers: [What should I put here?]) {
   let hotKey = HotKey(identifier: [What should I put here?], keyCombo: keyCombo, target: self, action: #selector())
   hotKey.register() // or HotKeyCenter.shared.register(with: hotKey)
}
```

Thank you very much!

**Comment by tommy19970714** [comment]
You can check the keycode in the following stackoverflow.
https://stackoverflow.com/questions/3202629/where-can-i-find-a-list-of-mac-virtual-key-codes

If you want to use command or control as shortcut key, you can write next code:
```
let keyCombo = KeyCombo(keyCode: 11, cocoaModifiers: [.command, .control])
```

I could tell you it because I found website that introduce how to use this framework:
https://qiita.com/econa77/items/a415f8d0fd834164506a

**Comment by 1c7** [comment]
@tommy19970714  Thanks! Didn’t except the content to be in Japanese. Still thanks anyway
